title = "chatbx.eu"
theme = "chatbx-theme"

languageCode = "en"
defaultContentLanguage = "en"

cleanDestinationDir = true
disableKinds = ["RSS", "taxonomy", "taxonomyTerm", "sitemap"]

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

summaryLength = 30
