[[main]]
	name = "Startseite"
	url = "/de/"
	weight = 1

[[main]]
	name = "Neuigkeiten"
	url = "/de/news/"
	weight = 2

[[main]]
	name = "Dokumentation"
	url = "/de/documentation/"
	weight = 3

[[main]]
	name = "Registrieren"
	url = "https://accounts.chatbx.eu/"
	weight = 4

[[main]]
	name = "Web Client"
	url = "https://web.chatbx.eu/"
	weight = 5


[[footer]]
	name = "Impressum"
	url = "/de/legal/imprint/"
	weight = 1

[[footer]]
	name = "Datenschutz"
	url = "/de/legal/privacy/"
	weight = 2

[[footer]]
	name = "Nutzungsbedingungen"
	url = "/de/legal/terms/"
	weight = 3
