[[main]]
	name = "Home"
	url = "/"
	weight = 1

[[main]]
	name = "News"
	url = "/news/"
	weight = 2

[[main]]
	name = "Documentation"
	url = "/documentation/"
	weight = 3

[[main]]
	name = "Account Registration"
	url = "https://accounts.chatbx.eu/"
	weight = 4

[[main]]
	name = "Web Client"
	url = "https://web.chatbx.eu/"
	weight = 5
