[homepage]
	button_text = 'Get Started'
	button_link = '/documentation/getting_started/'
	image = '/img/network.png'

	[homepage.meta]
		description = "chatbx.eu: Decentralized Instant Messaging with XMPP"
		og_title = "chatbx.eu"
		og_type = "website"
		og_url = "https://www.chatbx.eu/"
		og_image = "https://www.chatbx.eu/img/chatbx.png"
		og_description = "chatbx.eu: Decentralized Instant Messaging with XMPP"

[logo]
	mobile = "/img/chatbx.png"
	standard  = "/img/chatbx.png"
