[homepage]
	button_text = 'Loslegen'
	button_link = '/de/documentation/getting_started/'
	image = '/img/network.png'

	[homepage.meta]
		description = "Dezentralisiertes Instant Messaging mit XMPP"
		og_title = "chatbx.eu"
		og_type = "website"
		og_url = "https://www.chatbx.eu/de/"
		og_image = "https://www.chatbx.eu/img/chatbx.png"
		og_description = "Dezentralisiertes Instant Messaging mit XMPP"

[logo]
	mobile = "/img/chatbx.png"
	standard  = "/img/chatbx.png"
