baseURL = "/"
languageCode = "en"
defaultContentLanguage = "en"
title = "chatbx.eu"
themesDir = "themes"
theme = "hugo-whisper-theme"
publishdir = "/var/www/chatbx.eu/www.chatbx.eu/public/"
disableKinds = ["RSS"]

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 0

[languages]
	[languages.en]
		contentDir = "content/en"
		languageName = "English"
		weight = 1

		[[languages.en.menu.main]]
			name = "Home"
			url = "/"
			weight = 1

		[[languages.en.menu.main]]
			name = "Getting Started"
			url = "/documentation/getting_started/"
			weight = 2

		[[languages.en.menu.main]]
			name = "Documentation"
			url = "/documentation/"
			weight = 3

		[[languages.en.menu.main]]
			name = "Account Registration"
			url = "https://accounts.chatbx.eu/"
			weight = 4

		[[languages.en.menu.main]]
			name = "Web Client"
			url = "https://web.chatbx.eu/"
			weight = 5
			
		[languages.en.params]
			homepage_button_link = '/documentation/getting_started/'
			homepage_button_text = 'Get Started'
			homepage_intro = 'Decentralized Instant Messaging with XMPP.'
			homepage_image = '/img/network.png'

			[languages.en.params.homepage_meta_tags]
				meta_description = "chatbx.eu: Decentralized Instant Messaging with XMPP"
				meta_og_title = "chatbx.eu"
				meta_og_type = "website"
				meta_og_url = "https://www.chatbx.eu/"
				meta_og_image = "https://www.chatbx.eu/img/chatbx.png"
				meta_og_description = "chatbx.eu: Decentralized Instant Messaging with XMPP"

			[languages.en.params.logo]
				mobile = "/img/chatbx.png"
				standard  = "/img/chatbx.png"
				
			[languages.en.params.footer]
				language = "Language"
				imprint = "Imprint"
				privacy = "Privacy"
				termsofuse = "Terms of use"
				imprintUrl = "/legal/imprint/"
				privacyUrl = "/legal/privacy/"
                termsofuseUrl = "/legal/termsofuse/"

	
	[languages.de]
		contentDir = "content/de"
		languageName = "Deutsch"
		weight = 2

		[[languages.de.menu.main]]
			name = "Startseite"
			url = "/de/"
			weight = 1

		[[languages.de.menu.main]]
			name = "Loslegen"
			url = "/de/dokumentation/loslegen/"
			weight = 2

		[[languages.de.menu.main]]
			name = "Dokumentation"
			url = "/de/dokumentation/"
			weight = 3

		[[languages.de.menu.main]]
			name = "Registrieren"
			url = "https://accounts.chatbx.eu/"
			weight = 4

		[[languages.de.menu.main]]
			name = "Web Client"
			url = "https://web.chatbx.eu/"
			weight = 5
			
        [[languages.en.menu.main]]
			name = "Web Client"
			url = "https://web.chatbx.eu/"
			weight = 5
			
		[languages.de.params]
			homepage_button_link = '/de/dokumentation/loslegen/'
			homepage_button_text = 'Loslegen'
			homepage_intro = 'Dezentralisiertes Instant Messaging mit XMPP.'
			homepage_image = '/img/network.png'

			[languages.de.params.homepage_meta_tags]
				meta_description = "chatbx.eu: Dezentralisiertes Instant Messaging mit XMPP"
				meta_og_title = "chatbx.eu"
				meta_og_type = "website"
				meta_og_url = "https://www.chatbx.eu/de/"
				meta_og_image = "https://www.chatbx.eu/img/chatbx.png"
				meta_og_description = "chatbx.eu: Dezentralisiertes Instant Messaging mit XMPP"

			[languages.de.params.logo]
				mobile = "/img/chatbx.png"
				standard  = "/img/chatbx.png"
				
			[languages.de.params.footer]
				language = "Sprache"
				imprint = "Impressum"
				privacy = "Datenschutz"
				termsofuse = "Nutzungsbedingungen"
				imprintUrl = "/de/legal/impressum/"
				privacyUrl = "/de/legal/datenschutz/"
				termsofuseUrl = "/de/legal/nutzungsbedingungen/"

[privacy]
	[privacy.disqus]
		disable = true
	[privacy.googleAnalytics]
		disable = true
	[privacy.instagram]
		disable = true
	[privacy.twitter]
		disable = true
	[privacy.vimeo]
		disable = true
	[privacy.youtube]
		disable = true
